### ISSUE TITLE
Add my other games! (Racing Asylum)

### ISSUE THREAD

**Issue by EdgeKing810** [kinesisdownloads/kinesisdownloads.github.io#3]
Well, I'm a game dev. Having been done with Google Play, I decided to serve builds of my games on this website. Basically, you just need to create a page for one of my games, that's all. Description should be really brief. Apk download link and all details you need can be obtained from https://kinesisgames.net/. Please only create a page for the game mentioned in the title. Link a proper picture if possible too. Keep the format similar to Prototypes, the game already present on the website.

First one submitting a proper and quality PR has my green flag. Some basic knowledge and searching around how jekyll works will most likely help btw. Try grasping how everything works by for example reading the file in ``_posts/``. Makes use of markdown too so shouldn't be too hard.

>For beginners:
 >   * Fork this repo.
 >   * Clone **your** forked repo and make the required changes.
 >   * Can be previewed how the final page will look by opening ``index.html`` in a web browser.
 >   * Search about and submit a Pull Request!

**Comment by benknoble** [comment]
Happy to work on this, if all you need is description/image/download link

**Comment by EdgeKing810** [comment]
Just tell me and I'll assign you! Basically just another markdown file for another one of my games is needed.

**Comment by benknoble** [comment]
:+1: coming this weekend
